import getLocales from '@/utils/get-locales'
import getTranslations from '@/utils/get-translations'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import Providers from './providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const pageLocale = (await params).locale
  const { locales } = getLocales()
  const locale = locales.find((loc) => (loc.code = pageLocale))!

  const translations = getTranslations(locale.code)

  return (
    <html className="h-full" lang={locale.code}>
      <body
        className={`${geistSans.variable} flex min-h-full flex-col font-sans antialiased`}
      >
        <Providers locale={locale} translations={translations}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
